exports.List = [
  {
    name: "AMBASSADOR (AMB)",
    nilai: "AMBASSADOR",
    group: 1,
    status: false,
  },
  {
    name: "ADMINISTRATOR (ADM)",
    nilai: "ADMINISTRATOR",
    group: 22,
    status: false,
  },
  {
    name: "ANALYST (ANA)",
    nilai: "ANALYST",
    group: 29,
    status: false,
  },
  {
    name: "ARRANGER (ARR)",
    nilai: "ARRANGER",
    group: 3,
    status: false,
  },
  {
    name: "CARETAKER (CAR)",
    nilai: "CARETAKER",
    group: 8,
    status: false,
  },
  {
    name: "COMMANDER (CMD)",
    nilai: "COMMANDER",
    group: 4,
    status: false,
  },
  {
    name: "COMMUNICATOR (COM)",
    nilai: "COMMUNICATOR",
    group: 2,
    status: false,
  },
  {
    name: "CREATOR (CRE)",
    nilai: "CREATOR",
    group: 12,
    status: false,
  },
  {
    name: "DESIGNER (DES)",
    nilai: "DESIGNER",
    group: 11,
    status: false,
  },
  {
    name: "DISTRIBUTOR (DIS)",
    nilai: "DISTRIBUTOR",
    group: 18,
    status: false,
  },
  {
    name: "EDUCATOR (EDU)",
    nilai: "EDUCATOR",
    group: 30,
    status: false,
  },
  {
    name: "EVALUATOR (EVA)",
    nilai: "EVALUATOR",
    group: 27,
    status: false,
  },
  {
    name: "EXPLORER (EXP)",
    nilai: "EXPLORER",
    group: 25,
    status: false,
  },
  {
    name: "INTREPRETER (INT)",
    nilai: "INTREPRETER",
    group: 23,
    status: false,
  },
  {
    name: "JOURNALIST (JOU)",
    nilai: "JOURNALIST",
    group: 24,
    status: false,
  },
  {
    name: "MARKETER (MAR)",
    nilai: "MARKETER",
    group: 14,
    status: false,
  },
  {
    name: "MEDIATOR (MED)",
    nilai: "MEDIATOR",
    group: 5,
    status: false,
  },
  {
    name: "MOTIVATOR (MOT)",
    nilai: "MOTIVATOR",
    group: 31,
    status: false,
  },
  {
    name: "OPERATOR (OPE)",
    nilai: "OPERATOR",
    group: 17,
    status: false,
  },
  {
    name: "PRODUCER (PRO)",
    nilai: "PRODUCER",
    group: 21,
    status: false,
  },
  {
    name: "QUALITY CONTROLLER (QCA)",
    nilai: "QUALITY CONTROLLER",
    group: 20,
    status: false,
  },
  {
    name: "RESTORER (RES)",
    nilai: "RESTORER",
    group: 26,
    status: false,
  },
  {
    name: "SAFEKEEPER (SAF)",
    nilai: "SAFEKEEPER",
    group: 19,
    status: false,
  },
  {
    name: "SELLER (SEL)",
    nilai: "SELLER",
    group: 6,
    status: false,
  },
  {
    name: "SERVER (SER)",
    nilai: "SERVER",
    group: 9,
    status: false,
  },
  {
    name: "SELECTOR (SLC)",
    nilai: "SELECTOR",
    group: 7,
    status: false,
  },
  {
    name: "STRATEGIST (STR)",
    nilai: "STRATEGIST",
    group: 15,
    status: false,
  },
  {
    name: "SYNTHESIZER (SYN)",
    nilai: "SYNTHESIZER",
    group: 13,
    status: false,
  },
  {
    name: "TREASURE (TRE)",
    nilai: "TREASURE",
    group: 28,
    status: false,
  },
  {
    name: "VISIONARY (VIS)",
    nilai: "VISIONARY",
    group: 16,
    status: false,
  },
];
